#!/bin/bash

current_path=$(dirname $(realpath ${BASH_SOURCE[0]}))

lock() {
    # i3lock -c 151515
    i3lock -t -i "${_FILE}"
}

_FILE="${1}"; shift

case "$1" in
    lock)
        lock
        ;;
    logout)
        i3-msg exit
        ;;
    suspend)
        lock && systemctl suspend
        ;;
    hibernate)
        lock && systemctl hibernate
        ;;
    reboot)
        systemctl reboot
        ;;
    shutdown)
        systemctl poweroff
        ;;
    *)
        echo "Usage: $0 {lock|logout|suspend|hibernate|reboot|shutdown}"
        exit 2
esac

exit 0
